---
- name: Copy /etc/hummingbird/container-server.conf
  template:
    src: etc/container-server.j2
    dest: /etc/hummingbird/container-server.conf
    mode: 0644
    owner: hummingbird
    group: hummingbird
- name: Copy container server systemd files
  copy:
    src: systemd/hummingbird-container.service
    dest: /lib/systemd/system/hummingbird-container.service
    mode: 0644
- name: Start container service
  service:
    name: hummingbird-container
    enabled: yes
    state: restarted
- name: Copy container replicator systemd files
  copy:
    src: systemd/hummingbird-container-replicator.service
    dest: /lib/systemd/system/hummingbird-container-replicator.service
    mode: 0644
- name: Start container replicator service
  service:
    name: hummingbird-container-replicator
    enabled: yes
    state: restarted
